//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SPeerechisleniem
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Ответственный.
    /// </summary>
    // *** Start programmer edit section *** (Ответственный CustomAttributes)

    // *** End programmer edit section *** (Ответственный CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтветственныйE", new string[] {
            "Фамилия as \'Фамилия\'"})]
    [View("ОтветственныйL", new string[] {
            "Фамилия as \'Фамилия\'"})]
    public class Ответственный : ICSSoft.STORMNET.DataObject
    {
        
        private string fФамилия;
        
        // *** Start programmer edit section *** (Ответственный CustomMembers)

        // *** End programmer edit section *** (Ответственный CustomMembers)

        
        /// <summary>
        /// Фамилия.
        /// </summary>
        // *** Start programmer edit section *** (Ответственный.Фамилия CustomAttributes)

        // *** End programmer edit section *** (Ответственный.Фамилия CustomAttributes)
        [StrLen(255)]
        public virtual string Фамилия
        {
            get
            {
                // *** Start programmer edit section *** (Ответственный.Фамилия Get start)

                // *** End programmer edit section *** (Ответственный.Фамилия Get start)
                string result = this.fФамилия;
                // *** Start programmer edit section *** (Ответственный.Фамилия Get end)

                // *** End programmer edit section *** (Ответственный.Фамилия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ответственный.Фамилия Set start)

                // *** End programmer edit section *** (Ответственный.Фамилия Set start)
                this.fФамилия = value;
                // *** Start programmer edit section *** (Ответственный.Фамилия Set end)

                // *** End programmer edit section *** (Ответственный.Фамилия Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтветственныйE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтветственныйE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтветственныйE", typeof(IIS.SPeerechisleniem.Ответственный));
                }
            }
            
            /// <summary>
            /// "ОтветственныйL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтветственныйL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтветственныйL", typeof(IIS.SPeerechisleniem.Ответственный));
                }
            }
        }
    }
}
