//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SPeerechisleniem
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип накл.
    /// </summary>
    // *** Start programmer edit section *** (ТипНакл CustomAttributes)

    // *** End programmer edit section *** (ТипНакл CustomAttributes)
    public enum ТипНакл
    {
        
        // *** Start programmer edit section *** (ТипНакл.Приходная CustomAttributes)

        // *** End programmer edit section *** (ТипНакл.Приходная CustomAttributes)
        Приходная,
        
        // *** Start programmer edit section *** (ТипНакл.Расходная CustomAttributes)

        // *** End programmer edit section *** (ТипНакл.Расходная CustomAttributes)
        Расходная,
    }
}
